name: CD
on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOCKER_RUN_OPTS: ""
        run: |
          if [[ ${GITHUB_REF##*/} == "main" ]]; then
              export ENV_NAME=prod
          elif [[ ${GITHUB_REF##*/} == "develop" ]]; then
              export ENV_NAME=dev
          else
              echo "branch not deployed"
              exit 0
          fi
          envsubst < env.list.template > env.list
          make deploy
